version: '3.7'
services:
    jenkins:
        image: jenkinsci/blueocean
        ports:
            - "8000:8080"
        environment:
            DOCKER_HOST: tcp://docker:2376
        volumes:
            - jenkins-data:/var/jenkins_home
            - docker-certs:/certs/client:ro
        depends_on:
            - docker

    docker:
        image: docker:dind
        privileged: true
        environment:
            DOCKER_TLS_CERTDIR: /certs
        volumes:
            - docker-certs:/certs/client

volumes:
    jenkins-data:
    docker-certs:
